### ISSUE TITLE
[Feature] Copy image

### ISSUE THREAD

**Issue by ebouzekri** [Estia-1a/projetGenieInfo_public#21]
**Feature description**
Implement:
```c 
int copy_image(char* tocopy, char* destination)
``` 
- char* tocopy is the source file path
- char* destination is destination path
- return 0 if successful, 1 otherwise

**Describe tips for implementing feature**
You can use 
```c 
int read_image_data(const char *filename, unsigned char **data, int *width, int *height, int *nbChannels)
``` 
and 
```c 
int write_image_data(const char *filename, unsigned char *data, int width, int height)
```
from <estia-image.h>

**Comment by dhmmasson** [comment]
Moved to template
