### ISSUE TITLE
[Feature] Color in RGB

### ISSUE THREAD

**Issue by ebouzekri** [Estia-1a/projetGenieInfo_public#22]
**Feature description**
Transform the input image by keeping only the R (red) or G (green) or B (blue) component.
```c
int color_in_rgb(unsigned char* data, int w, int h, int n, int rgb, char* name, int output_format)
```
- data: Reference to the pointer that points to the pixel array
- w: Width of the image
- h: Height of the image
- n: Number of channels
- rgb: The channel to keep (0 = R only, 1 = G only, 2 = B only)
- name: The name of the ouput image

**Describe tips for implementing feature**
User getPixel from <utils.h>
```c
pixelRGB * getPixel( unsigned char* data, const unsigned int width, const unsigned int height, const unsigned int n, const unsigned int x, const unsigned int y )
```

**Additional information**
Add any other information or screenshots about the feature here.

**Comment by dhmmasson** [comment]
Moved to template
