### ISSUE TITLE
libraries in `template`

### ISSUE THREAD

**Issue by WilliamDelamare** [Estia-1a/projetGenieInfo_public#32]
The wiki states (section 3) that:

```
- Download https://github.com/Estia-1a/projetGenieInfo_public/releases/download/v2.0.1/estia-image-v2.0.1-win10-mingw64.zip TO CHANGE V3
- Put the content in estia-image/
- Download https://github.com/Estia-1a/projetGenieInfo_public/releases/download/v2.0.1/getopt-v2.0.1-win10-mingw64.zip TO CHANGE V3
- Put the content in get-opt/
```

* Why not directing to the full set of libraries? Why only ming64?
* The folders estia-image/ and get-opt/ are empty, so they are not created at the initial clone. Perhaps include a dummy file in each folder

**Comment by dhmmasson** [comment]
- While interesting to know that there are several architecture, we run the risk of having them download thing that don't compile ?
- I can agree with the second point, especially if the config in vscode.json / cmake is hardcoded to this specific folder
